global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'favorite-service'
    static_configs:
      - targets: ['favorite-service:5004']
    metrics_path: '/metrics'

  - job_name: 'rating-service'
    static_configs:
      - targets: ['rating-service:5003']
    metrics_path: '/metrics'

  - job_name: 'recipe-service'
    static_configs:
      - targets: ['recipe-service:5002']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5001']
    metrics_path: '/metrics'